# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

variables:
  vmImage: 'ubuntu-latest'
  dockerfilePath: '$(Build.SourcesDirectory)/docker/Dockerfile'

jobs:
  - job: BuildApi
    displayName: "Build Payment Gateway api"
    pool:
      vmImage: $(vmImage)

    steps:
    - task: Docker@2
      displayName: Build Docker Image
      inputs:
        command: build
        dockerfile: $(dockerfilePath)
        buildContext: $(Build.SourcesDirectory)

